export const DEFAULT_OUTPUT = "repo-context.md";
export const DEFAULT_MAX_TOKENS = 30000;
export const DEFAULT_TREE_DEPTH = 4;
export const DEFAULT_MAX_FILE_SIZE = 250000;

export const DEFAULT_IGNORE_PATTERNS = [
  ".git",
  ".git/**",
  "node_modules",
  "node_modules/**",
  "dist",
  "dist/**",
  "build",
  "build/**",
  "coverage",
  "coverage/**",
  ".next",
  ".next/**",
  ".nuxt",
  ".nuxt/**",
  ".turbo",
  ".turbo/**",
  ".cache",
  ".cache/**",
  ".venv",
  ".venv/**",
  "__pycache__",
  "__pycache__/**",
  ".pytest_cache",
  ".pytest_cache/**",
  "target",
  "target/**",
  "vendor",
  "vendor/**",
  ".DS_Store",
  "*.log",
  "*.tmp",
  "*.temp",
  "*.tsbuildinfo",
  "*.min.js",
  "*.min.css"
];

export const LOCK_FILE_NAMES = new Set([
  "package-lock.json",
  "npm-shrinkwrap.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "bun.lock",
  "bun.lockb",
  "Cargo.lock",
  "poetry.lock",
  "Pipfile.lock",
  "composer.lock",
  "Gemfile.lock",
  "go.sum",
  "uv.lock"
]);

export const MANIFEST_FILE_NAMES = new Set([
  "package.json",
  "pyproject.toml",
  "Cargo.toml",
  "go.mod",
  "pom.xml",
  "build.gradle",
  "build.gradle.kts",
  "requirements.txt",
  "composer.json",
  "Gemfile",
  "tsconfig.json",
  "jsconfig.json",
  "vite.config.ts",
  "vitest.config.ts"
]);

export const BINARY_EXTENSIONS = new Set([
  ".png",
  ".jpg",
  ".jpeg",
  ".gif",
  ".webp",
  ".ico",
  ".bmp",
  ".tiff",
  ".pdf",
  ".zip",
  ".gz",
  ".tgz",
  ".rar",
  ".7z",
  ".tar",
  ".exe",
  ".dll",
  ".so",
  ".dylib",
  ".class",
  ".jar",
  ".wasm",
  ".woff",
  ".woff2",
  ".ttf",
  ".otf",
  ".mp3",
  ".mp4",
  ".mov",
  ".avi",
  ".sqlite",
  ".db"
]);
