import fs from "node:fs/promises";
import path from "node:path";
import { estimateTokens } from "./tokens.js";
import type { OmittedFile, PreparedFile } from "./types.js";

export interface MarkdownInput {
  root: string;
  tokenBudget: number;
  tree: string;
  includedFiles: PreparedFile[];
  omittedFiles: OmittedFile[];
  maxFileSize: number;
  budgetWarning?: string;
}

export async function renderMarkdown(input: MarkdownInput): Promise<string> {
  const summary = await renderProjectSummary(input.root, input.includedFiles, input.omittedFiles);
  const generatedAt = new Date().toISOString();
  let approxTokens = 0;

  for (let index = 0; index < 5; index += 1) {
    const markdown = composeMarkdown(input, summary, generatedAt, approxTokens);
    const nextApproxTokens = estimateTokens(markdown);
    if (nextApproxTokens === approxTokens) {
      return markdown;
    }
    approxTokens = nextApproxTokens;
  }

  return composeMarkdown(input, summary, generatedAt, approxTokens);
}

function composeMarkdown(input: MarkdownInput, summary: string, generatedAt: string, approxTokens: number): string {
  const body = [
    "# Repository Context",
    "",
    "Generated by repo2ai.",
    "",
    "## Project Summary",
    "",
    summary,
    "",
    "## Metadata",
    "",
    `- Root: ${input.root}`,
    `- Generated: ${generatedAt}`,
    `- Files included: ${input.includedFiles.length}`,
    `- Files omitted: ${input.omittedFiles.length}`,
    `- Approx tokens: ${approxTokens}`,
    `- Token budget: ${input.tokenBudget}`,
    `- Max file size: ${input.maxFileSize} bytes`,
    "",
    input.budgetWarning ? `## Warning\n\n${input.budgetWarning}\n` : undefined,
    "## Suggested Prompt",
    "",
    "You are analyzing this codebase. Please understand the project structure first, then answer my question.",
    "",
    "## Directory Tree",
    "",
    "```text",
    input.tree,
    "```",
    "",
    "## Included Files",
    "",
    renderIncludedFilesTable(input.includedFiles),
    "",
    "## Omitted Files",
    "",
    renderOmittedFilesTable(input.omittedFiles),
    "",
    "## File Contents",
    "",
    renderFileContents(input.includedFiles)
  ].filter((section): section is string => section !== undefined);

  const markdown = body.join("\n");
  return markdown.endsWith("\n") ? markdown : `${markdown}\n`;
}

async function renderProjectSummary(root: string, includedFiles: PreparedFile[], omittedFiles: OmittedFile[]): Promise<string> {
  const packageName = await readPackageName(root);
  const extensionCounts = new Map<string, number>();

  for (const file of includedFiles) {
    const ext = path.posix.extname(file.path) || path.posix.basename(file.path);
    extensionCounts.set(ext, (extensionCounts.get(ext) ?? 0) + 1);
  }

  const topExtensions = [...extensionCounts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, 5)
    .map(([ext, count]) => `${ext} (${count})`)
    .join(", ");

  return [
    `- Project: ${packageName ?? path.basename(root)}`,
    `- Included files: ${includedFiles.length}`,
    `- Omitted files: ${omittedFiles.length}`,
    `- Main file types: ${topExtensions || "none"}`
  ].join("\n");
}

async function readPackageName(root: string): Promise<string | undefined> {
  try {
    const raw = await fs.readFile(path.join(root, "package.json"), "utf8");
    const parsed = JSON.parse(raw) as { name?: unknown };
    return typeof parsed.name === "string" ? parsed.name : undefined;
  } catch {
    return undefined;
  }
}

function renderIncludedFilesTable(files: PreparedFile[]): string {
  if (files.length === 0) {
    return "_No file contents included._";
  }

  return [
    "| Path | Priority | Size | Approx tokens | Notes |",
    "| --- | --- | ---: | ---: | --- |",
    ...files.map((file) => {
      const notes = file.redacted ? "redacted" : "";
      return `| \`${escapeTable(file.path)}\` | ${file.priority} | ${file.sizeBytes} | ${file.approxTokens} | ${notes} |`;
    })
  ].join("\n");
}

function renderOmittedFilesTable(files: OmittedFile[]): string {
  if (files.length === 0) {
    return "_No files omitted._";
  }

  return [
    "| Path | Reason | Size | Approx tokens |",
    "| --- | --- | ---: | ---: |",
    ...files.map((file) => {
      return `| \`${escapeTable(file.path)}\` | ${escapeTable(file.reason)} | ${file.sizeBytes ?? ""} | ${file.approxTokens ?? ""} |`;
    })
  ].join("\n");
}

function renderFileContents(files: PreparedFile[]): string {
  if (files.length === 0) {
    return "_No file contents included._\n";
  }

  return files
    .map((file) => {
      const fence = codeFenceFor(file.content);
      const language = file.language ? file.language : "";
      return [`### \`${file.path.replace(/`/g, "\\`")}\``, "", `${fence}${language}`, file.content, fence].join("\n");
    })
    .join("\n\n");
}

function codeFenceFor(content: string): string {
  let fence = "```";
  while (content.includes(fence)) {
    fence += "`";
  }
  return fence;
}

function escapeTable(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\n/g, " ");
}
